// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvmgnpiqerbxegroqczt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bWducGlxZXJieGVncm9xY3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTMwMjksImV4cCI6MjA1NTgyOTAyOX0.JDe4JxsRJtLAlra2aGFN6npO-BsNmRiO78fzL4-TqSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);